[package]
name = "elastic-objects-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
glam = "0.19.0"
glutin = "0.27.0"
glium = "0.30.2"
egui = "0.15.0"
egui_glium = "0.15.0"